#!/usr/bin/env python3
"""Build the shared Minecraft 1.11 recipe registry for Python and Netherite.

Inputs are the versioned ``recipes.json``, ``items.json`` and ``blocks.json``
files from PrismarineJS/minecraft-data. The checked-in outputs are generated;
runtime code never downloads data and the C engine and Python GUI expert are
therefore unable to drift onto different recipe lists.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


WILDCARD = 32767
SOURCE_COMMIT = "79f6aab42037d09acd09529baed87b62ccd48908"
SOURCE_URL = "https://github.com/PrismarineJS/minecraft-data"

# The 1.11 minecraft-data export resolved RecipesTools' ore-dictionary plank
# input to its final enum value (dark oak, metadata 5). Vanilla registers these
# generic outputs against WILDCARD_VALUE instead. Species-preserving outputs
# such as dark-oak stairs, fences, doors, and slabs intentionally stay exact.
GENERIC_PLANK_OUTPUTS = frozenset((
    "bed", "bookshelf", "bowl", "chest", "crafting_table", "jukebox",
    "noteblock", "piston", "shield", "sign", "stick", "trapdoor",
    "tripwire_hook", "wooden_axe", "wooden_button", "wooden_hoe",
    "wooden_pickaxe", "wooden_pressure_plate", "wooden_shovel",
    "wooden_sword",
))


def _ingredient(value):
    if value is None:
        return None
    if isinstance(value, int):
        return [value, WILDCARD]
    return [int(value["id"]), int(value.get("metadata", 0))]


def _normalized(recipes, items, blocks):
    item_names = {entry["name"]: int(entry["id"]) for entry in items}
    block_names = {entry["name"]: int(entry["id"]) for entry in blocks}
    names_by_id = {}
    for entry in items:
        names_by_id.setdefault(int(entry["id"]), entry["name"])
    variants = []
    order = 0
    for rows in recipes.values():
        for recipe in rows:
            result = recipe["result"]
            output_id = int(result["id"])
            record = {
                "output": [output_id, int(result.get("count", 1)),
                           int(result.get("metadata", 0))],
                "name": names_by_id.get(output_id, f"item_{output_id}"),
                "order": order,
            }
            order += 1
            if "inShape" in recipe:
                shape = [[_ingredient(value) for value in row]
                         for row in recipe["inShape"]]
                record["shape"] = shape
                record["size"] = len(shape) * len(shape[0])
                record["shaped"] = True
            else:
                ingredients = [_ingredient(value)
                               for value in recipe["ingredients"]]
                record["ingredients"] = ingredients
                record["size"] = len(ingredients)
                record["shaped"] = False
            if record["name"] in GENERIC_PLANK_OUTPUTS:
                values = ([value for row in record.get("shape", ())
                           for value in row]
                          if record["shaped"] else record["ingredients"])
                for value in values:
                    if value == [5, 5]:
                        value[1] = WILDCARD
            variants.append(record)

    # CraftingManager 1.11 sorts shaped recipes before shapeless recipes and
    # larger layouts before smaller ones. Preserve source order as the final
    # tie-breaker so overlapping layouts resolve like the game.
    variants.sort(key=lambda row: (
        0 if row["shaped"] else 1, -row["size"], row["order"]))
    for row in variants:
        row.pop("order")
        row.pop("size")

    return {
        "schema": "bedrock.minecraft-recipes.v1",
        "minecraft": "1.11.2",
        "source": {"repository": SOURCE_URL, "commit": SOURCE_COMMIT,
                   "license": "MIT", "dataset": "pc/1.11"},
        "items": dict(sorted(item_names.items())),
        "blocks": dict(sorted(block_names.items())),
        "stack_sizes": {str(entry["id"]): int(entry.get("stackSize", 64))
                        for entry in items},
        "durability": {str(entry["id"]): int(entry["maxDurability"])
                       for entry in items if entry.get("maxDurability")},
        "recipes": variants,
    }


def _c_stack(value):
    if value is None:
        return "crf_empty()"
    item, meta = value
    return f"crf_mk({item},1,{meta})"


def _header(data):
    recipes = data["recipes"]
    lines = [
        "/* Generated by bedrock-rl/tools/build_recipe_registry.py.",
        " * Minecraft 1.11.2 standard shaped/shapeless recipe registry.",
        f" * Source: {SOURCE_URL} @ {SOURCE_COMMIT} (MIT).",
        " */",
        "#ifndef MC_CRAFTING_RECIPES_FULL_H",
        "#define MC_CRAFTING_RECIPES_FULL_H",
        '#include "mc.h"',
        "#define CRF_WILDCARD 32767",
        "typedef struct { i32 item; i32 count; i32 meta; } CRStack;",
        "MC_HD static inline CRStack crf_empty(void){CRStack s={0,0,0};return s;}",
        "MC_HD static inline CRStack crf_mk(i32 i,i32 n,i32 m){CRStack s={i,n,m};return s;}",
        "MC_HD static inline int crf_isEmpty(CRStack s){return s.item==0||s.count<=0;}",
        "typedef struct { int shaped,width,height,nIng; CRStack ing[9],output; } CRRecipe;",
        "#define CRF_GRID 3",
        "MC_HD static inline int crf_checkMatch(const CRRecipe*r,const CRStack*g,int ox,int oy,int mirror){",
        " for(int i=0;i<3;++i)for(int j=0;j<3;++j){int k=i-ox,l=j-oy;CRStack in=crf_empty();",
        "  if(k>=0&&l>=0&&k<r->width&&l<r->height)in=mirror?r->ing[r->width-k-1+l*r->width]:r->ing[k+l*r->width];",
        "  CRStack v=g[i+j*3];if(!crf_isEmpty(v)||!crf_isEmpty(in)){if(crf_isEmpty(v)!=crf_isEmpty(in))return 0;",
        "   if(in.item!=v.item)return 0;if(in.meta!=CRF_WILDCARD&&in.meta!=v.meta)return 0;}}return 1;}",
        "MC_HD static inline int crf_shapedMatches(const CRRecipe*r,const CRStack*g){",
        " for(int x=0;x<=3-r->width;++x)for(int y=0;y<=3-r->height;++y)",
        "  if(crf_checkMatch(r,g,x,y,1)||crf_checkMatch(r,g,x,y,0))return 1;return 0;}",
        "MC_HD static inline int crf_shapelessMatches(const CRRecipe*r,const CRStack*g){",
        " int used[9]={0},left=r->nIng;for(int i=0;i<9;++i)if(!crf_isEmpty(g[i])){int hit=0;",
        "  for(int z=0;z<r->nIng;++z)if(!used[z]&&g[i].item==r->ing[z].item&&",
        "   (r->ing[z].meta==CRF_WILDCARD||g[i].meta==r->ing[z].meta)){used[z]=1;--left;hit=1;break;}",
        "  if(!hit)return 0;}return left==0;}",
        "MC_HD static inline int crf_matches(const CRRecipe*r,const CRStack*g){",
        " return r->shaped?crf_shapedMatches(r,g):crf_shapelessMatches(r,g);}",
        "MC_HD static inline CRStack crf_findMatching(const CRRecipe*r,int n,const CRStack*g){",
        " for(int i=0;i<n;++i)if(crf_matches(&r[i],g))return r[i].output;return crf_mk((i32)0xffffffff,0,0);}",
        f"#define CRF_NRECIPES {len(recipes)}",
        "#define CRF_NTESTS 1",
        "MC_HD static inline int crf_build(CRRecipe *R){int n=0;",
    ]
    for recipe in recipes:
        output = recipe["output"]
        if recipe["shaped"]:
            shape = recipe["shape"]
            ingredients = [value for row in shape for value in row]
            width, height = len(shape[0]), len(shape)
            lines.append(
                f" R[n].shaped=1;R[n].width={width};R[n].height={height};"
                f"R[n].nIng={len(ingredients)};")
        else:
            ingredients = recipe["ingredients"]
            lines.append(
                f" R[n].shaped=0;R[n].width=0;R[n].height=0;"
                f"R[n].nIng={len(ingredients)};")
        lines.append(
            f" R[n].output=crf_mk({output[0]},{output[1]},{output[2]});")
        for index, value in enumerate(ingredients):
            lines.append(f" R[n].ing[{index}]={_c_stack(value)};")
        lines.append(" ++n;")
    # Keep Netherite's standalone crafting-kernel target buildable and make
    # its one generated smoke case exercise a recipe that was absent from the
    # old 95-entry KEEP table.
    comparator = next(row for row in recipes if row["name"] == "comparator")
    cells = [value for row in comparator["shape"] for value in row]
    lines += [" return n;}",
              "MC_HD static inline void crf_battery(CRStack out[CRF_NTESTS][9]){"]
    for index, value in enumerate(cells):
        lines.append(f" out[0][{index}]={_c_stack(value)};")
    lines += ["}", "#endif", ""]
    return "\n".join(lines)


def _items_header(data):
    lines = [
        "/* Generated by bedrock-rl/tools/build_recipe_registry.py.",
        " * Minecraft 1.11.2 item stack sizes and durability.",
        f" * Source: {SOURCE_URL} @ {SOURCE_COMMIT} (MIT).",
        " */",
        "#ifndef MC_ITEM_REGISTRY_FULL_H",
        "#define MC_ITEM_REGISTRY_FULL_H",
        '#include "mc.h"',
        "MC_HD static inline i32 mcr_max_stack_size(i32 item){switch(item){",
    ]
    for item, size in sorted(
            ((int(item), int(size)) for item, size
             in data["stack_sizes"].items())):
        if size != 64:
            lines.append(f" case {item}: return {size};")
    lines += [" default:return 64;}}",
              "MC_HD static inline i32 mcr_max_durability(i32 item){switch(item){"]
    for item, durability in sorted(
            ((int(item), int(value)) for item, value
             in data["durability"].items())):
        lines.append(f" case {item}: return {durability};")
    lines += [" default:return 0;}}", "#endif", ""]
    return "\n".join(lines)


def _write(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(text)
    temporary.replace(path)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--recipes", required=True)
    parser.add_argument("--items", required=True)
    parser.add_argument("--blocks", required=True)
    parser.add_argument("--json", required=True)
    parser.add_argument("--header", required=True)
    parser.add_argument("--items-header", required=True)
    args = parser.parse_args()
    load = lambda path: json.loads(Path(path).read_text())
    data = _normalized(load(args.recipes), load(args.items),
                       load(args.blocks))
    _write(args.json, json.dumps(data, separators=(",", ":"),
                                 sort_keys=True) + "\n")
    _write(args.header, _header(data))
    _write(args.items_header, _items_header(data))
    print(f"recipes={len(data['recipes'])} outputs="
          f"{len({row['output'][0] for row in data['recipes']})}")


if __name__ == "__main__":
    main()
