#!/usr/bin/env python3
"""Generate netherite's texture headers without a Minecraft jar.

The engine reads no PNG at runtime. Every texture it draws is a C array in
one of thirteen generated headers under magma/assets, and upstream builds
those headers from a vanilla 1.11.2 client jar you have to own. That jar is
the only thing in the whole stack a user cannot obtain by cloning, so this
script removes it.

HOW. It does not reimplement the thirteen generators. It writes a synthetic
resource pack, a real zip laid out exactly like the jar with a procedurally
drawn PNG at every path those generators read, and then runs
scripts/bootstrap_assets.sh against it. So the headers come out with the
struct shapes, symbol names, sprite counts and atlas rects the engine
already compiles against, because the engine's own generators produced them.
Only the texels differ. A stub header is then given a provenance banner
saying so, because the generator's own comment still claims Mojang art.

WHAT THE ART IS. Nothing invented. Where the engine already has a
procedural fallback it is left to use it, so a GUI item cell gets the flat
token gm_hud_pip_color would have drawn anyway. Where it draws from an
atlas, three numbers per texture decide the result and all three are
measured rather than chosen.

The colour comes from netherite's own block palette, the COLORS table in
blaze/rl/make_videos.py that colourises the semantic camera in their
README, for every block id it covers. Everything else takes the mean colour
of the vanilla 1.11.2 texture, and the two agree where both exist, exactly
for dirt at (134,96,67) and sand at (219,211,160). The second number is
that texture's texel-to-texel spread and the third is how much of it is
opaque. Matching a palette is not copying art, and without the spread a
tile at the right mean renders as a flat slab, which is what made the first
pass look like a smooth tunnel underground and like wireframe on grass.

Container panels reproduce vanilla's grey chrome, its bevel and its
recessed slot squares, so the container screens look the same and the pixel
container geometry stays aligned with the engine's screen layout.

DETERMINISM IS THE POINT. Two clones that disagree about a texel present
different model inputs even when their engine state matches. Nothing here
reads a clock, a
filesystem order or python's salted hash. Colours and noise come from an
FNV-1a of the sprite name through a fixed xorshift, and every PNG is written
at its final size in its final mode so no resampling ever runs. Generating
twice gives byte-identical headers, and `--print-digests` is how you check
that rather than take it on trust.

  uv run --no-project --with pillow python tools/stub_atlases.py \
      --netherite-home ~/netherite

MC_JAR still wins. bin/setup_deps.sh calls this only when no jar is given.
"""
import argparse
import hashlib
import io
import json
import os
import subprocess
import sys
import tempfile
import zipfile

# One number in every generated header. Bump it when the drawing changes, so
# a rebuilt engine is visibly not the one an old rollout ran against.
STUB_VERSION = 1

TEX = "assets/minecraft/textures/"

# The banner prepended to each generated header. The generator that wrote
# the file below it says "Real MC 1.11.2", which under this path is false.
BANNER = """/* STUB TEXTURES, generated by bedrock-rl tools/stub_atlases.py v%d.
 * This build carries NO Mojang content. The engine's own asset generator
 * ran against a synthetic resource pack, so the struct shapes, symbol
 * names and atlas rects below are the real ones and only the texels are
 * procedural. The "Real MC 1.11.2" wording in the comment that follows is
 * that generator's, and does not apply here. Rebuild with MC_JAR set to a
 * client jar you own to get the real art. */
""" % STUB_VERSION

HEADERS = ("atlas_gen.h", "colormap_gen.h", "gui_atlas.h", "hand_atlas.h",
           "hud_atlas.h", "inventory_ui_atlas.h", "item_atlas.h",
           "loading_bg.h", "mob_atlas.h", "portal_tex.h", "sky_atlas.h",
           "underwater_tex.h", "water_frames.h")


# ---------------------------------------------------------------- randomness
def fnv(s):
    """FNV-1a over the sprite name. Python's hash() is salted per process
    and would make the build differ between two runs on one machine."""
    h = 0x811C9DC5
    for b in s.encode():
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


class Rng:
    """xorshift32. Deterministic, seeded from a name, no library state."""

    def __init__(self, seed):
        self.s = (seed & 0xFFFFFFFF) or 0x9E3779B9

    def next(self):
        x = self.s
        x ^= (x << 13) & 0xFFFFFFFF
        x ^= x >> 17
        x ^= (x << 5) & 0xFFFFFFFF
        self.s = x
        return x

    def below(self, n):
        return self.next() % n

    def spread(self, n):
        """A signed value in [-n, n]."""
        return self.below(2 * n + 1) - n


def clamp(v):
    return 0 if v < 0 else 255 if v > 255 else int(v)


def shade(rgb, d):
    return (clamp(rgb[0] + d), clamp(rgb[1] + d), clamp(rgb[2] + d))


def hsv(h, s, v):
    """h,s,v in [0,1] to an 8-bit RGB triple. Integer-free but exact enough,
    and identical on every platform because it never touches libm."""
    i = int(h * 6) % 6
    f = h * 6 - int(h * 6)
    p, q, t = v * (1 - s), v * (1 - s * f), v * (1 - s * (1 - f))
    r, g, b = ((v, t, p), (q, v, p), (p, v, t),
               (p, q, v), (t, p, v), (v, p, q))[i]
    return (clamp(round(r * 255)), clamp(round(g * 255)), clamp(round(b * 255)))


# ------------------------------------------------------------------- palette
# The container-panel greys. Vanilla's chrome is flat grey with a two pixel
# light bevel, a two pixel shadow and recessed slot squares, and the stub
# reproduces it rather than inventing a palette, so the screens read the same
# across procedurally generated container textures. These values are the
# single definition of that palette in this repo.
PANEL_FACE = (198, 198, 198)
PANEL_LIGHT = (255, 255, 255)
PANEL_SHADOW = (85, 85, 85)
SLOT_FACE = (139, 139, 139)
SLOT_SHADOW = (55, 55, 55)
PANEL_EDGE = (0, 0, 0)

# netherite's own block palette, blaze/rl/make_videos.py COLORS, block id to
# rgb. It is what colourises the semantic camera in their README, so it is
# the repo's own statement of what each block is meant to look like.
NETHERITE_COLORS = {
    0: (110, 165, 255), 1: (128, 128, 128), 2: (95, 159, 53),
    3: (134, 96, 67), 4: (100, 100, 100), 7: (40, 40, 40),
    8: (47, 90, 200), 9: (47, 90, 200), 10: (230, 120, 30),
    11: (230, 120, 30), 12: (219, 211, 160), 13: (136, 126, 126),
    14: (143, 140, 125), 15: (135, 130, 126), 16: (105, 105, 105),
    17: (155, 106, 56), 18: (32, 105, 28), 24: (215, 205, 158),
    31: (74, 132, 50), 32: (123, 79, 25), 37: (255, 220, 60),
    38: (215, 60, 60), 78: (240, 248, 255), 79: (145, 180, 235),
    82: (158, 164, 176), 86: (222, 126, 34), 99: (140, 110, 90),
    100: (200, 60, 60), 106: (25, 90, 25), 175: (60, 140, 60),
}

# Which texture each palette id paints. Only the ids whose colour IS the
# texture's own are here. Grass 2, leaves 18, tallgrass 31, vine 106 and
# double plant 175 are deliberately absent: their palette entry is what you
# see AFTER the biome colormap multiplies a near-grey texture, so authoring
# the texture at that value would apply the green twice and come out black.
# Those keep the vanilla grey below and let the colormap supply the colour.
PALETTE_TEXTURES = {
    1: ("stone",), 3: ("dirt",), 4: ("cobblestone",), 7: ("bedrock",),
    8: ("water_still", "water_flow"), 10: ("lava_still", "lava_flow"),
    12: ("sand",), 13: ("gravel",), 14: ("gold_ore",), 15: ("iron_ore",),
    16: ("coal_ore",), 17: ("log_oak",),
    24: ("sandstone_normal", "sandstone_top", "sandstone_bottom"),
    32: ("deadbush",), 37: ("flower_dandelion",), 38: ("flower_rose",),
    78: ("snow",), 79: ("ice",), 82: ("clay",),
    86: ("pumpkin_side", "pumpkin_top"),
    99: ("mushroom_block_skin_brown",), 100: ("mushroom_block_skin_red",),
}
PALETTE_BY_NAME = {n: NETHERITE_COLORS[i]
                   for i, names in PALETTE_TEXTURES.items() for n in names}

# The renderer darkens everything on the way to the framebuffer, so a
# texture authored AT the palette renders below it. Measured rather than
# guessed: an engine whose every block is a flat 200 grey, player looking
# straight down at the top face of the block below in open sky, sampled
# across a whole world day.
#
#   world tick 0        121 of 200      the clock the world starts on
#   world tick 1000+    178 of 200      full daylight, and flat until dusk
#   world tick 14000    58 of 200       night, and tinted blue
#
# So a lit top face lands at 0.89 of what the texture holds, and the
# authored value is the palette divided by that. Two things follow.
#
# The first is that a stub build is about a tenth brighter than a jar build,
# because vanilla's own textures are authored at the palette rather than
# above it. That is deliberate: the palette is netherite's statement of what
# a block looks like, and hitting it on screen is the point.
#
# The second is worth knowing for any frame, not just these. Episodes start
# at world tick 0, which is the dim end of the curve, and a few hundred
# ticks never reach daylight. Short recordings are therefore lit at about
# 0.6 rather than 0.89. That is the clock, not the art.
DAYLIGHT_FACE = 0.89


def lit(rgb):
    """Authored albedo whose lit top face reads as `rgb`."""
    return tuple(clamp(round(v / DAYLIGHT_FACE)) for v in rgb)


# Grass, leaves and the other biome-tinted textures are near-grey in vanilla
# and the colormap supplies their colour, so their albedo is one flat value
# and the colormaps below are solved to land on the palette through it.
TINTED_GREY = 200
TINTED = set()
for _n in ("grass_top", "grass_side_overlay", "tallgrass", "fern", "vine",
           "waterlily", "double_plant_grass_bottom", "double_plant_grass_top",
           "double_plant_fern_bottom", "double_plant_fern_top"):
    TINTED.add(_n)

# Everything else, measured off the vanilla 1.11.2 textures: the mean colour,
# the texel-to-texel spread of that texture's luminance, and how much of it
# is opaque. Three numbers per texture, not a copy of one, and the palette
# above agrees with them where both exist, exactly for dirt (134,96,67) and
# sand (219,211,160). The spread is what was missing before. A tile authored
# at the right mean with almost no variation renders as a flat slab, which is
# what made the underground read as a smooth tunnel rather than as rock.
# The coverage is why a canopy is not a black wall: vanilla oak leaves are
# only 61 percent opaque and the sky comes through the rest.
VANILLA = {
    "bedrock": ((84, 84, 84), 75, 1.00),
    "bone_block_side": ((225, 221, 201), 10, 1.00),
    "bone_block_top": ((206, 201, 178), 31, 1.00),
    "brick": ((147, 100, 87), 51, 1.00),
    "cactus_bottom": ((163, 186, 123), 113, 0.77),
    "cactus_side": ((14, 102, 25), 45, 0.91),
    "cactus_top": ((13, 100, 24), 49, 0.77),
    "clay": ((159, 164, 177), 12, 1.00),
    "coal_ore": ((115, 115, 115), 45, 1.00),
    "coarse_dirt": ((119, 86, 59), 45, 1.00),
    "cobblestone": ((123, 123, 123), 51, 1.00),
    "cobblestone_mossy": ((104, 121, 104), 62, 1.00),
    "crafting_table_front": ((115, 95, 64), 100, 1.00),
    "crafting_table_side": ((119, 96, 60), 91, 1.00),
    "crafting_table_top": ((107, 71, 43), 78, 1.00),
    "deadbush": ((124, 80, 25), 42, 0.32),
    "destroy_stage_0": ((108, 108, 108), 81, 0.02),
    "destroy_stage_1": ((99, 99, 99), 80, 0.04),
    "destroy_stage_2": ((98, 98, 98), 79, 0.07),
    "destroy_stage_3": ((101, 101, 101), 81, 0.11),
    "destroy_stage_4": ((102, 102, 102), 81, 0.16),
    "destroy_stage_5": ((102, 102, 102), 81, 0.21),
    "destroy_stage_6": ((101, 101, 101), 81, 0.27),
    "destroy_stage_7": ((102, 102, 102), 81, 0.39),
    "destroy_stage_8": ((102, 102, 102), 81, 0.50),
    "destroy_stage_9": ((101, 101, 101), 81, 0.57),
    "diamond_ore": ((129, 140, 143), 57, 1.00),
    "dirt": ((134, 96, 67), 40, 1.00),
    "dirt_podzol_side": ((123, 88, 57), 45, 1.00),
    "dirt_podzol_top": ((91, 63, 29), 28, 1.00),
    "double_plant_fern_bottom": ((124, 124, 124), 46, 0.62),
    "double_plant_fern_top": ((125, 125, 125), 46, 0.48),
    "double_plant_grass_bottom": ((140, 140, 140), 40, 0.54),
    "double_plant_grass_top": ((147, 147, 147), 42, 0.36),
    "double_plant_paeonia_bottom": ((55, 89, 59), 78, 0.58),
    "double_plant_paeonia_top": ((132, 134, 142), 129, 0.51),
    "double_plant_rose_bottom": ((70, 64, 3), 34, 0.73),
    "double_plant_rose_top": ((116, 61, 8), 34, 0.42),
    "double_plant_sunflower_back": ((64, 105, 42), 11, 0.20),
    "double_plant_sunflower_bottom": ((65, 109, 43), 23, 0.20),
    "double_plant_sunflower_front": ((234, 198, 34), 37, 0.20),
    "double_plant_sunflower_top": ((68, 112, 45), 21, 0.11),
    "double_plant_syringa_bottom": ((143, 149, 132), 57, 0.34),
    "double_plant_syringa_top": ((148, 148, 140), 51, 0.33),
    "emerald_ore": ((110, 129, 116), 51, 1.00),
    "end_stone": ((221, 224, 165), 37, 1.00),
    "endframe_eye": ((40, 72, 67), 70, 0.38),
    "endframe_side": ((148, 160, 124), 128, 0.81),
    "endframe_top": ((89, 117, 96), 112, 1.00),
    "fern": ((120, 120, 120), 45, 0.31),
    "fire_layer_0": ((213, 142, 53), 91, 0.57),
    "fire_layer_1": ((217, 151, 54), 85, 0.61),
    "flower_allium": ((178, 141, 211), 42, 0.15),
    "flower_blue_orchid": ((38, 152, 138), 48, 0.18),
    "flower_dandelion": ((108, 162, 1), 105, 0.12),
    "flower_houstonia": ((162, 192, 139), 102, 0.17),
    "flower_oxeye_daisy": ((176, 198, 139), 107, 0.17),
    "flower_rose": ((101, 58, 4), 31, 0.14),
    "flower_tulip_orange": ((96, 134, 32), 27, 0.20),
    "flower_tulip_pink": ((102, 150, 73), 71, 0.19),
    "flower_tulip_red": ((103, 135, 39), 30, 0.19),
    "flower_tulip_white": ((95, 153, 66), 89, 0.19),
    "furnace_front_off": ((78, 78, 78), 95, 1.00),
    "furnace_side": ((113, 113, 113), 79, 1.00),
    "furnace_top": ((96, 96, 96), 58, 1.00),
    "glass": ((218, 241, 244), 37, 0.28),
    "glass_pane_top": ((212, 240, 244), 35, 0.12),
    "glowstone": ((144, 118, 70), 99, 1.00),
    "gold_ore": ((143, 140, 125), 65, 1.00),
    "grass_side": ((127, 107, 66), 48, 1.00),
    "grass_side_overlay": ((143, 143, 143), 25, 0.18),
    "grass_top": ((147, 147, 147), 31, 1.00),
    "gravel": ((127, 124, 123), 38, 1.00),
    "hardened_clay": ((151, 93, 67), 6, 1.00),
    "hardened_clay_stained_white": ((210, 178, 161), 4, 1.00),
    "hopper_inside": ((56, 56, 56), 9, 1.00),
    "hopper_outside": ((63, 63, 63), 15, 1.00),
    "hopper_top": ((67, 67, 67), 13, 0.61),
    "ice": ((125, 173, 255), 31, 1.00),
    "ice_packed": ((165, 195, 245), 13, 1.00),
    "iron_bars": ((110, 108, 106), 51, 0.45),
    "iron_ore": ((136, 130, 127), 35, 1.00),
    "ladder": ((121, 95, 53), 49, 0.56),
    "lapis_ore": ((102, 112, 135), 46, 1.00),
    "lava_flow": ((207, 92, 21), 38, 1.00),
    "lava_still": ((217, 105, 26), 43, 1.00),
    "leaves_acacia": ((135, 135, 135), 63, 0.61),
    "leaves_big_oak": ((135, 135, 135), 63, 0.61),
    "leaves_birch": ((135, 135, 135), 63, 0.61),
    "leaves_jungle": ((145, 143, 134), 48, 0.79),
    "leaves_oak": ((135, 135, 135), 63, 0.61),
    "leaves_spruce": ((116, 116, 116), 69, 0.65),
    "log_acacia": ((105, 99, 89), 37, 1.00),
    "log_acacia_top": ((154, 91, 64), 21, 1.00),
    "log_big_oak": ((52, 41, 23), 23, 1.00),
    "log_big_oak_top": ((78, 62, 41), 30, 1.00),
    "log_birch": ((207, 206, 201), 104, 1.00),
    "log_birch_top": ((184, 166, 122), 74, 1.00),
    "log_jungle": ((87, 68, 27), 30, 1.00),
    "log_jungle_top": ((154, 119, 73), 58, 1.00),
    "log_oak": ((102, 81, 50), 45, 1.00),
    "log_oak_top": ((155, 125, 77), 57, 1.00),
    "log_spruce": ((46, 29, 12), 29, 1.00),
    "log_spruce_top": ((105, 81, 48), 34, 1.00),
    "magma": ((135, 65, 25), 77, 1.00),
    "melon_side": ((141, 146, 36), 47, 1.00),
    "melon_top": ((151, 154, 37), 40, 1.00),
    "mob_spawner": ((26, 40, 49), 9, 0.61),
    "mushroom_block_inside": ((203, 171, 121), 20, 1.00),
    "mushroom_block_skin_brown": ((142, 107, 83), 20, 1.00),
    "mushroom_block_skin_red": ((183, 38, 36), 52, 1.00),
    "mushroom_brown": ((138, 106, 84), 50, 0.10),
    "mushroom_red": ((195, 54, 56), 84, 0.13),
    "mycelium_side": ((114, 88, 74), 47, 1.00),
    "mycelium_top": ((111, 100, 105), 18, 1.00),
    "nether_brick": ((45, 23, 27), 14, 1.00),
    "netherrack": ((111, 54, 53), 70, 1.00),
    "obsidian": ((20, 18, 30), 21, 1.00),
    "planks_oak": ((157, 128, 79), 45, 1.00),
    "portal": ((89, 12, 192), 34, 1.00),
    "pumpkin_side": ((197, 121, 24), 45, 1.00),
    "pumpkin_top": ((193, 118, 21), 50, 1.00),
    "quartz_block_bottom": ((232, 228, 220), 9, 1.00),
    "quartz_block_side": ((236, 233, 226), 9, 1.00),
    "quartz_block_top": ((236, 233, 226), 9, 1.00),
    "quartz_ore": ((125, 85, 80), 115, 1.00),
    "rail_normal": ((121, 109, 89), 60, 0.56),
    "red_sandstone_bottom": ((163, 83, 28), 11, 1.00),
    "red_sandstone_normal": ((166, 85, 30), 13, 1.00),
    "red_sandstone_top": ((167, 85, 30), 5, 1.00),
    "redstone_ore": ((133, 107, 107), 47, 1.00),
    "reeds": ((149, 193, 101), 48, 0.55),
    "sand": ((219, 211, 160), 24, 1.00),
    "sandstone_bottom": ((213, 205, 148), 24, 1.00),
    "sandstone_normal": ((217, 210, 157), 28, 1.00),
    "sandstone_top": ((218, 210, 159), 11, 1.00),
    "slime": ((121, 200, 101), 17, 1.00),
    "snow": ((240, 251, 251), 12, 1.00),
    "soul_sand": ((85, 64, 52), 42, 1.00),
    "stone": ((125, 125, 125), 20, 1.00),
    "stone_andesite": ((131, 131, 131), 41, 1.00),
    "stone_andesite_smooth": ((133, 133, 135), 35, 1.00),
    "stone_diorite": ((180, 180, 183), 62, 1.00),
    "stone_diorite_smooth": ((183, 183, 186), 63, 1.00),
    "stone_granite": ((153, 114, 99), 61, 1.00),
    "stone_granite_smooth": ((159, 115, 98), 42, 1.00),
    "stone_slab_side": ((167, 167, 167), 36, 1.00),
    "stone_slab_top": ((159, 159, 159), 28, 1.00),
    "stonebrick": ((122, 122, 122), 31, 1.00),
    "tallgrass": ((136, 136, 136), 31, 0.64),
    "tnt_bottom": ((170, 77, 51), 47, 1.00),
    "tnt_side": ((170, 93, 71), 109, 1.00),
    "tnt_top": ((130, 65, 47), 74, 1.00),
    "torch_on": ((130, 106, 58), 110, 0.08),
    "trapdoor": ((127, 93, 46), 40, 0.86),
    "vine": ((111, 111, 111), 51, 0.54),
    "water_flow": ((49, 72, 244), 15, 1.00),
    "water_still": ((47, 67, 244), 12, 1.00),
    "waterlily": ((119, 119, 119), 42, 0.58),
    "web": ((220, 220, 220), 25, 0.41),
    "wool_colored_white": ((222, 222, 222), 32, 1.00),
}

# Structure on top of the tone, where a block has some. Everything absent is
# plain grain, which is most of them.
PATTERNS = {
    "planks_oak": "planks", "crafting_table_side": "planks",
    "crafting_table_top": "grid", "crafting_table_front": "tools",
    "cobblestone": "rubble", "cobblestone_mossy": "rubble",
    "gravel": "rubble", "bedrock": "rubble",
    "stonebrick": "brick", "brick": "brick", "nether_brick": "brick",
    "coal_ore": "ore", "iron_ore": "ore", "gold_ore": "ore",
    "diamond_ore": "ore", "redstone_ore": "ore", "lapis_ore": "ore",
    "emerald_ore": "ore", "quartz_ore": "ore",
    "grass_side": "grass_side", "grass_side_overlay": "fringe",
    "furnace_front_off": "furnace", "furnace_top": "grid",
    "water_still": "water", "water_flow": "water", "portal": "water",
    "lava_still": "lava", "lava_flow": "lava",
    "mob_spawner": "cage", "tnt_side": "tnt",
    "glass": "glassy",
}
for _n in list(VANILLA):
    if _n.startswith("leaves_"):
        PATTERNS.setdefault(_n, "leaves")
        TINTED.add(_n)
    elif _n.startswith("destroy_stage_"):
        PATTERNS.setdefault(_n, "cracks")
    elif _n.startswith("log_") and _n.endswith("_top"):
        PATTERNS.setdefault(_n, "rings")
    elif _n.startswith("log_"):
        PATTERNS.setdefault(_n, "bark")

# Cross-shaped plants and other cutouts. Value is the drawing routine, and
# the colour still comes from tone_of.
CUTOUTS = {
    "tallgrass": "plant", "fern": "plant", "deadbush": "plant",
    "reeds": "plant", "vine": "plant", "waterlily": "pad",
    "mushroom_brown": "shroom", "mushroom_red": "shroom",
    "iron_bars": "bars", "glass_pane_top": "edge", "ladder": "ladder",
    "rail_normal": "rail", "web": "web", "torch_on": "torch",
    "glass": "glassy",
}
for _p in ("flower_dandelion", "flower_rose", "flower_blue_orchid",
           "flower_allium", "flower_houstonia", "flower_tulip_red",
           "flower_tulip_orange", "flower_tulip_white", "flower_tulip_pink",
           "flower_oxeye_daisy"):
    CUTOUTS[_p] = "flower"
for _p in ("double_plant_grass_bottom", "double_plant_grass_top",
           "double_plant_fern_bottom", "double_plant_fern_top",
           "double_plant_sunflower_bottom", "double_plant_sunflower_top",
           "double_plant_sunflower_front", "double_plant_sunflower_back",
           "double_plant_syringa_bottom", "double_plant_syringa_top",
           "double_plant_rose_bottom", "double_plant_rose_top",
           "double_plant_paeonia_bottom", "double_plant_paeonia_top"):
    CUTOUTS[_p] = "plant"

# Every block texture assets/build_atlas.py asks the jar for, plus the six
# animated strips assets/build_water_frames.py reads and the portal strip
# assets/build_portal.py reads. This list tracks the pinned engine; a name
# it is missing surfaces immediately as a KeyError out of the generator.
BLOCK_NAMES = sorted(set([
    "bedrock", "coarse_dirt", "dirt", "dirt_podzol_side", "dirt_podzol_top",
    "grass_side", "grass_side_overlay", "grass_top", "gravel",
    "hardened_clay", "hardened_clay_stained_white", "ice", "mycelium_side",
    "mycelium_top", "red_sandstone_bottom", "red_sandstone_normal",
    "red_sandstone_top", "sand", "sandstone_bottom", "sandstone_normal",
    "sandstone_top", "snow", "stone", "water_flow", "water_still",
    "waterlily", "leaves_oak", "leaves_birch", "leaves_spruce",
    "leaves_acacia", "leaves_jungle", "leaves_big_oak", "log_oak",
    "log_oak_top", "log_birch", "log_birch_top", "log_spruce",
    "log_spruce_top", "log_acacia", "log_acacia_top", "log_jungle",
    "log_jungle_top", "log_big_oak", "log_big_oak_top", "tallgrass", "fern",
    "deadbush", "flower_dandelion", "flower_rose", "flower_blue_orchid",
    "flower_allium", "flower_houstonia", "flower_tulip_red",
    "flower_tulip_orange", "flower_tulip_white", "flower_tulip_pink",
    "flower_oxeye_daisy", "reeds", "double_plant_grass_bottom",
    "double_plant_grass_top", "double_plant_fern_bottom",
    "double_plant_fern_top", "double_plant_sunflower_bottom",
    "double_plant_sunflower_top", "double_plant_sunflower_front",
    "double_plant_sunflower_back", "double_plant_syringa_bottom",
    "double_plant_syringa_top", "double_plant_rose_bottom",
    "double_plant_rose_top", "double_plant_paeonia_bottom",
    "double_plant_paeonia_top", "mushroom_brown", "mushroom_red", "vine",
    "glass", "lava_flow", "lava_still", "planks_oak", "rail_normal",
    "furnace_front_off", "furnace_side", "furnace_top", "hopper_inside",
    "hopper_outside", "hopper_top", "tnt_bottom", "tnt_side", "tnt_top",
    "crafting_table_top", "crafting_table_front", "crafting_table_side",
    "cobblestone", "cobblestone_mossy", "stone_granite",
    "stone_granite_smooth", "stone_diorite", "stone_diorite_smooth",
    "stone_andesite", "stone_andesite_smooth", "coal_ore", "iron_ore",
    "gold_ore", "redstone_ore", "diamond_ore", "lapis_ore", "emerald_ore",
    "clay", "obsidian", "netherrack", "nether_brick", "portal", "end_stone",
    "glowstone", "soul_sand", "fire_layer_0", "fire_layer_1", "magma",
    "quartz_ore", "endframe_side", "endframe_top", "endframe_eye",
    "iron_bars", "torch_on", "bone_block_side", "bone_block_top",
    "cactus_side", "cactus_top", "cactus_bottom", "pumpkin_side",
    "pumpkin_top", "melon_side", "melon_top", "mushroom_block_skin_brown",
    "mushroom_block_skin_red", "mushroom_block_inside", "mob_spawner",
    "destroy_stage_0", "destroy_stage_1", "destroy_stage_2",
    "destroy_stage_3", "destroy_stage_4", "destroy_stage_5",
    "destroy_stage_6", "destroy_stage_7", "destroy_stage_8",
    "destroy_stage_9", "ice_packed", "slime", "web", "wool_colored_white",
    "quartz_block_bottom", "quartz_block_side", "quartz_block_top",
    "stone_slab_side", "stone_slab_top", "stonebrick", "glass_pane_top",
    "trapdoor", "ladder", "brick",
]))

# name -> (frames, frametime, sprite size, sequence length). The six strips
# assets/build_water_frames.py reads plus the portal strip. Frame counts and
# frame times match vanilla so the animations run at the same speed.
ANIMATED = {
    "water_still": (32, 2, 16, 32),
    "water_flow": (32, 1, 32, 32),
    "lava_still": (20, 2, 16, 38),
    "lava_flow": (16, 3, 32, 16),
    "fire_layer_0": (32, 1, 16, 32),
    "fire_layer_1": (32, 1, 16, 32),
}
PORTAL_FRAMES = 32

# 16x16 item sprites, the union of what assets/build_item_atlas.py,
# assets/build_gui_atlas.py and assets/build_inventory_ui_atlas.py read.
ITEM_NAMES = sorted(set([
    "iron_shovel", "iron_pickaxe", "iron_axe", "flint_and_steel", "apple",
    "bow_standby", "arrow", "coal", "diamond", "iron_ingot", "gold_ingot",
    "iron_sword", "wood_sword", "wood_shovel", "wood_pickaxe", "wood_axe",
    "stone_sword", "stone_shovel", "stone_pickaxe", "stone_axe",
    "diamond_sword", "diamond_shovel", "diamond_pickaxe", "diamond_axe",
    "stick", "string", "feather", "gunpowder", "seeds_wheat", "wheat",
    "bread", "flint", "porkchop_raw", "porkchop_cooked", "bucket_empty",
    "bucket_water", "bucket_lava", "leather", "egg", "bone", "bed",
    "beef_raw", "beef_cooked", "chicken_raw", "chicken_cooked",
    "rotten_flesh", "ender_pearl", "blaze_rod", "blaze_powder", "ender_eye",
    "redstone_dust", "reeds", "gold_sword", "bow_pulling_0", "bow_pulling_1",
    "bow_pulling_2", "fireball", "empty_armor_slot_helmet",
    "empty_armor_slot_chestplate", "empty_armor_slot_leggings",
    "empty_armor_slot_boots", "empty_armor_slot_shield",
]))

# What each mob skin's native size has to be, because build_mob_atlas.py
# shelf-packs at native resolution and the rects are part of the header the
# engine compiles against.
MOBS = [
    ("zombie/zombie.png", 64, 64), ("skeleton/skeleton.png", 64, 32),
    ("creeper/creeper.png", 64, 32), ("spider/spider.png", 64, 32),
    ("enderman/enderman.png", 64, 32), ("blaze.png", 64, 32),
    ("sheep/sheep.png", 64, 32), ("sheep/sheep_fur.png", 64, 32),
    ("pig/pig.png", 64, 32), ("cow/cow.png", 64, 32),
    ("chicken.png", 64, 32), ("squid.png", 64, 32),
    ("zombie_pigman.png", 64, 64), ("zombie/husk.png", 64, 64),
    ("skeleton/stray.png", 64, 32),
    ("skeleton/wither_skeleton.png", 64, 32),
    ("spider/cave_spider.png", 64, 32), ("cow/mooshroom.png", 64, 32),
    ("witch.png", 64, 128), ("bat.png", 64, 64),
    ("llama/llama_creamy.png", 128, 64), ("ghast/ghast.png", 64, 32),
    ("slime/magmacube.png", 64, 32), ("minecart.png", 64, 32),
    ("projectiles/arrow.png", 32, 32),
    ("endercrystal/endercrystal.png", 128, 64),
    ("enderdragon/dragon.png", 256, 256), ("armorstand/wood.png", 64, 64),
    ("experience_orb.png", 64, 64), ("slime/slime.png", 64, 32),
    ("silverfish.png", 64, 32), ("boat/boat_oak.png", 128, 64),
    ("enderdragon/dragon_exploding.png", 256, 256),
    ("explosion.png", 128, 128),
    ("endercrystal/endercrystal_beam.png", 16, 256),
    ("shield_base_nopattern.png", 64, 64),
    ("enderdragon/dragon_fireball.png", 16, 16),
    ("steve.png", 64, 64), ("alex.png", 64, 64),
    ("end_portal.png", 256, 256),
]
ARMOR_LAYERS = ("iron_layer_1", "iron_layer_2",
                "diamond_layer_1", "diamond_layer_2")

# Slot content origins in panel space, exactly gm_screen_layout's numbers.
# The recess a slot sits in is the 18x18 square one pixel up and left.
PITCH = 18
INV_MAIN = [(8 + (i % 9) * PITCH, 84 + (i // 9) * PITCH) for i in range(27)]
INV_HOTBAR = [(8 + i * PITCH, 142) for i in range(9)]


# --------------------------------------------------------------- drawing kit
def img(w, h, fill=(0, 0, 0, 0)):
    from PIL import Image
    return Image.new("RGBA", (w, h), fill)


def px_of(im):
    return im.load()


def tone_of(name, index, total):
    """(colour, texel spread, opaque fraction) for one block texture.

    netherite's palette wins where it covers the block, the measured vanilla
    tone covers the rest, and the golden angle is only for a name neither
    knows. Consecutive golden-angle indices land two fifths of the way round
    the hue circle, so any run of unknown blocks stays separated."""
    if name in TINTED:
        # one flat grey, because the colormap is what carries the colour and
        # the two are solved together
        _, spread, cover = VANILLA.get(name, (None, 34, 1.0))
        g = TINTED_GREY
        return (g, g, g), spread, cover
    if name in ORE_FLECK:
        # The FACE of an ore is plain stone in vanilla and the fleck is the
        # whole cue. Taking the texture's own mean instead tints the rock
        # with the ore, which both looks wrong and eats the contrast the
        # fleck is there to provide: it put lapis on blue rock and gold on
        # yellow rock, so face and fleck sat a few dE apart.
        host = "netherrack" if name == "quartz_ore" else "stone"
        base, spread, cover = VANILLA[host]
        return lit(base), max(spread, VANILLA[name][1] // 2), cover
    if name in PALETTE_BY_NAME:
        _, spread, cover = VANILLA.get(name, (None, 34, 1.0))
        return lit(PALETTE_BY_NAME[name]), spread, cover
    if name in VANILLA:
        base, spread, cover = VANILLA[name]
        return lit(base), spread, cover
    r = Rng(fnv(name))
    hue = (index * 0.6180339887498949) % 1.0
    return lit(hsv(hue, 0.35 + r.below(30) / 100.0,
                   0.42 + r.below(38) / 100.0)), 34, 1.0


def pattern_of(name):
    return PATTERNS.get(name, "grain")


# Ore flecks, measured off a jar build's rendered faces. This is the one
# accent that cannot come from the tile's own tone: vanilla ores all share
# the same grey stone face and the fleck colour IS the whole cue. Deriving
# it from the base, which is what every other pattern does, put all seven
# ores within a few dE of each other and of their own stone, which quietly
# turned ore-discrimination tasks into a test of something else.
#
# These are ALBEDOS, read off the jar-built atlas the same way every other
# number in VANILLA was, and they go through lit() like the rest. Rendered
# fleck means were available too and were not used directly, because a
# rendered number is only meaningful next to the face factor it was taken
# at: gold measures (122,116,83) rendered, which divided by DAYLIGHT_FACE
# gives (137,130,93) and not the (252,225,117) the texture actually holds,
# because that reading came off a face shaded nearer 0.48 than 0.89. Mixing
# the two spaces is the mistake that made the whole world dark one revision
# ago, so the fleck is measured where the tone is measured.
ORE_FLECK = {
    "coal_ore": (58, 58, 58),
    "iron_ore": (200, 163, 138),
    "gold_ore": (252, 225, 117),
    "diamond_ore": (153, 230, 251),
    "lapis_ore": (24, 64, 177),
    "redstone_ore": (180, 2, 2),
    "emerald_ore": (67, 205, 114),
    "quartz_ore": (219, 206, 194),
}


def accent_of(name, base, spread):
    """A structural mark reads against the grain rather than through it, so
    it is pitched one spread below the tone rather than at a fixed step.

    Ores are the exception and carry their own colour, because theirs is
    not a mark ON the material, it is the material the block is named for.
    """
    if name in ORE_FLECK:
        return lit(ORE_FLECK[name])
    return shade(base, -max(10, spread // 3))


def fill_material(p, w, h, base, spread, rng):
    """Two octaves of grain at the vanilla spread.

    One octave is either mush or static. A coarse four pixel cell carries the
    block's own variation, which is what stops a wall of one block reading as
    a single flat slab, and the per-texel octave carries the material.

    Note what is NOT here: a darker pixel around the tile. Faces do have to
    stay countable, but a rim baked into a texture that tiles across a
    terrain surface joins up into a continuous grid, which is why the grass
    looked like wireframe. Separation is the renderer's job and it already
    does it, by shading each face off its normal.
    """
    cw = w // 4 + 1
    coarse = [[rng.spread(spread) * 7 // 10 for _ in range(cw)]
              for _ in range(h // 4 + 1)]
    for y in range(h):
        row = coarse[y // 4]
        for x in range(w):
            # the coarse octave carries most of it on purpose. A texture is
            # minified to a few pixels at any distance, and per-texel grain
            # averages away there while block-scale clumps survive, which is
            # what makes a rock wall read as rock rather than as a gradient.
            d = row[x // 4] + rng.spread(spread) * 35 // 100
            c = [clamp(base[k] + d) for k in range(3)]
            if spread > 20 and rng.below(32) == 0:
                # a mineral fleck. Vanilla dirt and gravel carry a handful of
                # grey texels that are nothing like the rest of the tile, and
                # they are most of why a wall of one block does not read as a
                # single colour once it is minified.
                g = (c[0] + c[1] + c[2]) // 3
                c = [clamp((v + 3 * g) // 4 + rng.spread(spread // 3))
                     for v in c]
            p[x, y] = (c[0], c[1], c[2], 255)


def block_tile(name, index, total, size=16, salt=0):
    """One block texture: base colour, a pattern, a darker rim.

    `salt` is the animation frame. Folding it into the seed is what
    makes a water or lava strip move rather than repeat one still."""
    base, spread, cover = tone_of(name, index, total)
    pat = pattern_of(name)
    accent = accent_of(name, base, spread)
    rng = Rng(fnv(name) ^ 0x5BF03635 ^ (salt * 0x9E3779B1))
    im = img(size, size)
    p = px_of(im)
    cut = CUTOUTS.get(name)

    if cut:
        _cutout(p, size, cut, base, accent, rng)
        return im

    fill_material(p, size, size, base, spread, rng)

    if pat == "planks":
        # a plank edge is a dark line with a lit one under it, which is what
        # separates the boards at a distance where the grain has averaged out
        for y in range(size):
            if y % 4 == 3:
                for x in range(size):
                    p[x, y] = shade(base, -max(16, spread // 2)) + (255,)
            elif y % 4 == 0:
                for x in range(size):
                    p[x, y] = shade(base, max(8, spread // 4)) + (255,)
        for y in range(size):
            if y % 8 < 3:
                p[(fnv(name) + y) % size, y] = accent + (255,)
    elif pat == "bark":
        for x in range(size):
            if (x + rng.below(2)) % 4 == 0:
                for y in range(size):
                    p[x, y] = shade(accent, rng.spread(6)) + (255,)
    elif pat == "rings":
        c = (size - 1) / 2.0
        for y in range(size):
            for x in range(size):
                d = int(max(abs(x - c), abs(y - c)))
                if d % 4 == 0:
                    p[x, y] = shade(accent, 16 + rng.spread(5)) + (255,)
    elif pat == "grid":
        for i in range(size):
            p[i, size // 2] = accent + (255,)
            p[size // 2, i] = accent + (255,)
            p[i, 0] = accent + (255,)
            p[0, i] = accent + (255,)
    elif pat == "tools":
        # the crafting-table face: a dark frame with two marks in it, so it
        # cannot be confused with a plank or a log side
        for i in range(2, size - 2):
            p[i, 2] = accent + (255,)
            p[i, size - 3] = accent + (255,)
            p[2, i] = accent + (255,)
            p[size - 3, i] = accent + (255,)
        for i in range(4, size - 4):
            p[i, i] = shade(accent, 20) + (255,)
            p[size - 1 - i, i] = shade(accent, 20) + (255,)
    elif pat == "brick":
        for y in range(size):
            if y % 4 == 0:
                for x in range(size):
                    p[x, y] = accent + (255,)
            elif y % 8 < 4:
                p[(y // 4 * 3) % size, y] = accent + (255,)
            else:
                p[(y // 4 * 3 + 8) % size, y] = accent + (255,)
    elif pat == "rubble":
        for _ in range(size * 3):
            x, y = rng.below(size), rng.below(size)
            p[x, y] = shade(accent, rng.spread(10)) + (255,)
    elif pat == "ore":
        # seven 2x2 clusters, each shaded a little so the ore reads as
        # mineral in rock rather than as flat stickers
        for _ in range(7):
            x, y = 2 + rng.below(size - 4), 2 + rng.below(size - 4)
            for k, (dx, dy) in enumerate(((0, 0), (1, 0), (0, 1), (1, 1))):
                d = rng.spread(12) + (6 if k == 0 else -6 if k == 3 else 0)
                p[x + dx, y + dy] = shade(accent, d) + (255,)
    elif pat == "leaves":
        # punch holes to the measured coverage, which for oak is 61 percent.
        # Solid leaves turn a canopy into a black ceiling; the sky coming
        # through the gaps is most of what makes a forest readable.
        holes = int(round(size * size * (1.0 - cover)))
        placed = 0
        guard = 0
        while placed < holes and guard < size * size * 8:
            guard += 1
            x, y = rng.below(size), rng.below(size)
            if p[x, y][3]:
                p[x, y] = (0, 0, 0, 0)
                placed += 1
    elif pat == "cracks":
        stage = int(name.rsplit("_", 1)[1]) if name[-1].isdigit() else 0
        im2 = img(size, size)
        p2 = px_of(im2)
        for _ in range((stage + 1) * 6):
            x, y = rng.below(size), rng.below(size)
            for k in range(rng.below(4) + 1):
                p2[min(size - 1, x + k), min(size - 1, y + k)] = (0, 0, 0, 190)
        return im2
    elif pat == "water":
        for y in range(size):
            for x in range(size):
                d = rng.spread(max(6, spread))
                p[x, y] = (clamp(base[0] + d), clamp(base[1] + d),
                           clamp(base[2] + d), 200)
        return im
    elif pat == "lava":
        for _ in range(size * 2):
            x, y = rng.below(size), rng.below(size)
            p[x, y] = shade(accent, rng.spread(12)) + (255,)
    elif pat == "furnace":
        for y in range(7, size - 2):
            for x in range(3, size - 3):
                p[x, y] = accent + (255,)
        for x in range(4, size - 4):
            p[x, size - 4] = (150, 150, 150, 255)
    elif pat == "cage":
        for i in range(0, size, 3):
            for j in range(size):
                p[i, j] = accent + (255,)
                p[j, i] = accent + (255,)
    elif pat == "tnt":
        for y in range(6, 10):
            for x in range(size):
                p[x, y] = accent + (255,)
    elif pat == "grass_side":
        for y in range(4):
            for x in range(size):
                d = rng.spread(max(8, spread // 2))
                p[x, y] = (clamp(accent[0] + d), clamp(accent[1] + d),
                           clamp(accent[2] + d), 255)
        for x in range(size):
            if rng.below(2):
                p[x, 4] = accent + (255,)
    elif pat == "fringe":
        im2 = img(size, size)
        p2 = px_of(im2)
        for y in range(size):
            for x in range(size):
                keep = y < 3 or (y < 6 and (x + y + rng.below(2)) % 2 == 0)
                if keep:
                    d = rng.spread(max(8, spread // 2))
                    p2[x, y] = (clamp(base[0] + d), clamp(base[1] + d),
                                clamp(base[2] + d), 255)
        return im2
    elif pat == "glassy":
        im2 = img(size, size)
        p2 = px_of(im2)
        for i in range(size):
            for x, y in ((i, 0), (i, size - 1), (0, i), (size - 1, i)):
                p2[x, y] = base + (255,)
        for i in range(2, size - 2, 5):
            p2[i, i] = base + (150,)
        return im2

    return im


def _cutout(p, size, kind, base, accent, rng):
    """Shapes that need transparency. A cross plant drawn as a solid square
    renders as a coloured slab standing in the grass, which is worse than
    wrong: it looks like a block the agent could mine."""
    def put(x, y, c, a=255):
        if 0 <= x < size and 0 <= y < size:
            p[x, y] = (c[0], c[1], c[2], a)

    mid = size // 2
    if kind in ("plant", "flower", "shroom"):
        stem = shade(base, -30) if kind != "shroom" else shade(base, -20)
        for y in range(mid - 2 if kind == "shroom" else 2, size):
            put(mid, y, stem)
            if kind == "plant" and y % 3 == 0:
                put(mid - 1 - rng.below(2), y, base)
                put(mid + 1 + rng.below(2), y, base)
        if kind == "flower":
            for dx in range(-2, 3):
                for dy in range(-2, 3):
                    if abs(dx) + abs(dy) <= 2:
                        put(mid + dx, 4 + dy, base)
        elif kind == "shroom":
            for dx in range(-4, 5):
                for dy in range(-2, 2):
                    if abs(dx) + abs(dy) <= 4:
                        put(mid + dx, mid + dy, base)
    elif kind == "pad":
        for y in range(size):
            for x in range(size):
                if abs(x - mid) + abs(y - mid) <= mid:
                    put(x, y, shade(base, rng.spread(8)))
    elif kind == "bars":
        for x in (mid - 1, mid):
            for y in range(size):
                put(x, y, base)
    elif kind == "edge":
        for x in range(size):
            for y in (0, 1):
                put(x, y, base)
    elif kind == "ladder":
        for y in range(size):
            put(2, y, base)
            put(size - 3, y, base)
        for y in range(2, size, 4):
            for x in range(2, size - 2):
                put(x, y, shade(base, 18))
    elif kind == "rail":
        for x in (4, size - 5):
            for y in range(size):
                put(x, y, (150, 150, 155))
        for y in range(1, size, 4):
            for x in range(2, size - 2):
                put(x, y, shade(base, -10))
    elif kind == "web":
        for i in range(size):
            put(i, i, (236, 236, 236))
            put(size - 1 - i, i, (236, 236, 236))
            if i % 4 == 0:
                for x in range(size):
                    put(x, i, (210, 210, 210))
    elif kind == "torch":
        for y in range(size // 2, size):
            put(mid, y, (140, 100, 50))
            put(mid - 1, y, (120, 86, 44))
        for dy in range(3):
            for dx in range(-1, 2):
                put(mid + dx, size // 2 - 1 - dy, accent)
    elif kind == "glassy":
        for i in range(size):
            for x, y in ((i, 0), (i, size - 1), (0, i), (size - 1, i)):
                put(x, y, base)


def item_icon(name, index, total, size=16):
    """A flat coloured token, which is what the engine's own pip fallback
    draws when a sprite is missing. Making it a shape would be inventing art
    the engine does not need; the colour is what tells two items apart."""
    r = Rng(fnv(name))
    if name.startswith("empty_armor_slot_"):
        # Slot.getSlotTexture's hints. Vanilla draws a dim silhouette on the
        # slot grey, and a bright colour here would read as a held item.
        im = img(size, size)
        p = px_of(im)
        for y in range(4, size - 3):
            for x in range(4, size - 3):
                if (x + y) % 7:
                    p[x, y] = (96, 96, 96, 255)
        return im
    hue = (index * 0.6180339887498949 + 0.13) % 1.0
    mat = {"wood_": (0.09, 0.55), "stone_": (0.0, 0.02), "iron_": (0.0, 0.05),
           "gold_": (0.13, 0.85), "diamond_": (0.5, 0.7)}
    sat, val = 0.55 + r.below(25) / 100.0, 0.62 + r.below(28) / 100.0
    for pre, (h, s) in mat.items():
        if name.startswith(pre):
            hue, sat = h, s
            break
    base = hsv(hue, sat, val)
    im = img(size, size)
    p = px_of(im)
    for y in range(2, size - 2):
        for x in range(2, size - 2):
            edge = x in (2, size - 3) or y in (2, size - 3)
            p[x, y] = (shade(base, -40) if edge else
                       shade(base, r.spread(8))) + (255,)
    return im


# ------------------------------------------------------------- panel drawing
def panel(w, h):
    """Vanilla container chrome: black outline, two pixel light bevel top and
    left, two pixel shadow bottom and right, flat face between them, corners
    cut. Reproduced procedurally rather than lifted, and the five greys are
    the module constants above."""
    im = img(w, h)
    p = px_of(im)
    for y in range(h):
        for x in range(w):
            dl, dt, dr, db = x, y, w - 1 - x, h - 1 - y
            if min(dl + dt, dr + dt, dl + db, dr + db) < 2:
                continue                                   # cut corner
            if min(dl, dt, dr, db) == 0:
                p[x, y] = PANEL_EDGE + (255,)
                continue
            light = dt <= 2 or dl <= 2 or dt + dl <= 6
            dark = db <= 2 or dr <= 2 or db + dr <= 6
            if light and dark:
                light = min(dt, dl) <= min(db, dr)
                dark = not light
            p[x, y] = ((PANEL_LIGHT if light else
                        PANEL_SHADOW if dark else PANEL_FACE) + (255,))
    return im


def slot(p, x, y, size=16):
    """One recessed slot. Content is size x size at (x,y); the recess is the
    square one pixel up and left, dark on its top and left and light on its
    bottom and right, which is what makes it read as a hole."""
    for i in range(-1, size + 1):
        p[x + i, y - 1] = SLOT_SHADOW + (255,)
        p[x - 1, y + i] = SLOT_SHADOW + (255,)
        p[x + i, y + size] = PANEL_LIGHT + (255,)
        p[x + size, y + i] = PANEL_LIGHT + (255,)
    p[x + size, y - 1] = SLOT_FACE + (255,)
    for j in range(size):
        for i in range(size):
            p[x + i, y + j] = SLOT_FACE + (255,)


def arrow(p, x, y, w, h, colour):
    """The grid-to-result arrow vanilla draws into the panel itself. Without
    it a screen shows two slot groups and no relation between them, which is
    exactly the thing the agent has to understand."""
    head = min(h, w)
    shaft = max(2, h // 3)
    top = y + (h - shaft) // 2
    for j in range(shaft):
        for i in range(w - head + 1):
            p[x + i, top + j] = colour + (255,)
    for j in range(head):
        reach = min(j, head - 1 - j)
        for i in range(reach + 1):
            p[x + w - head + i, y + j] = colour + (255,)


def sheet(im, w=256, h=256):
    """Drop a panel into the 256x256 sheet the generators crop from."""
    out = img(w, h)
    out.paste(im, (0, 0))
    return out


def inventory_png():
    im = panel(176, 166)
    p = px_of(im)
    for x, y in INV_MAIN + INV_HOTBAR:
        slot(p, x, y)
    for k in range(4):                                   # armour column
        slot(p, 8, 8 + k * PITCH)
    slot(p, 77, 62)                                      # offhand
    for i in range(4):                                   # 2x2 matrix
        slot(p, 98 + (i % 2) * PITCH, 18 + (i // 2) * PITCH)
    slot(p, 154, 28)                                     # its result
    arrow(p, 135, 28, 17, 11, SLOT_FACE)
    out = sheet(im)
    q = px_of(out)
    # GuiIngame.renderPotionEffects reads a 24x24 background at (141,166)
    # and an 8x3 grid of 18x18 icons at (0,198).
    small = panel(24, 24)
    out.paste(small, (141, 166))
    for i in range(24):
        cx, cy = (i % 8) * 18, 198 + (i // 8) * 18
        col = hsv((i * 0.6180339887498949) % 1.0, 0.6, 0.8)
        for y in range(2, 16):
            for x in range(2, 16):
                q[cx + x, cy + y] = col + (255,)
    return out


def crafting_table_png():
    im = panel(176, 166)
    p = px_of(im)
    for x, y in INV_MAIN + INV_HOTBAR:
        slot(p, x, y)
    for i in range(9):
        slot(p, 30 + (i % 3) * PITCH, 17 + (i // 3) * PITCH)
    slot(p, 124, 35)
    arrow(p, 92, 37, 26, 13, SLOT_FACE)
    return sheet(im)


def furnace_png():
    im = panel(176, 166)
    p = px_of(im)
    for x, y in INV_MAIN + INV_HOTBAR:
        slot(p, x, y)
    slot(p, 56, 17)
    slot(p, 56, 53)
    slot(p, 116, 35, 16)
    # the unlit arrow under GuiFurnace's progress sprite, same rect
    arrow(p, 79, 34, 24, 17, SLOT_FACE)
    out = sheet(im)
    q = px_of(out)
    # GuiFurnace's two progress sprites, read at (176,0,14x14) and
    # (176,14,24x17). The flame is revealed from its bottom row up and the
    # arrow from its left column right, so both are drawn solid.
    for y in range(14):
        half = 7 - abs(7 - y)
        for x in range(7 - half, 7 + half + 1):
            hot = y > 8 or abs(x - 7) < 2
            q[176 + x, y] = ((250, 214, 90) if hot else (238, 140, 30)) + (255,)
    for y in range(16):
        if 4 <= y <= 11:
            for x in range(17):
                q[176 + x, 14 + y] = (238, 238, 238, 255)
        arm = abs(y - 8)
        for x in range(17, 24):
            if x - 17 < 7 - arm:
                q[176 + x, 14 + y] = (238, 238, 238, 255)
    return out


def generic_54_png():
    """The chest sheet. GuiChest composites rows 0..70 with rows 126..221, so
    the panel is drawn full height and both halves come out of one frame."""
    im = panel(176, 222)
    p = px_of(im)
    for r in range(6):
        for c in range(9):
            slot(p, 8 + c * PITCH, 18 + r * PITCH)
    for j in range(27):
        slot(p, 8 + (j % 9) * PITCH, 140 + (j // 9) * PITCH)
    for i in range(9):
        slot(p, 8 + i * PITCH, 198)
    return sheet(im)


# ------------------------------------------------------------------- the HUD
# 9x9 HUD icons, drawn rather than blobbed. A diamond is not a heart, and
# the row of them is the most looked-at thing on the screen.
HEART = ("..##.##..", ".#######.", ".#######.", ".#######.",
         "..#####..", "...###...", "....#....", ".........", ".........")
HAUNCH = ("..###....", ".#####...", ".#####...", "..####...",
          "...###...", "....##...", ".....##..", "......#..", ".........")
ARMOUR = ("..#####..", ".##.#.##.", "#########", "#########",
          "#########", ".#######.", "..#####..", "...###...", ".........")
BUBBLE = ("..#####..", ".##...##.", "#..###..#", "#.#####.#",
          "#.#####.#", "#..###..#", ".##...##.", "..#####..", ".........")


def stencil(p, x0, y0, rows, colour, rng, amp=6):
    """Draw one 9x9 HUD icon with the dark outline vanilla bakes into its.

    Without the outline a heart sitting on a bright sky is a pale smear.
    The shapes are all narrow enough to grow by a pixel inside their cell."""
    h, w = len(rows), len(rows[0])
    edge = shade(colour, -90)
    for y in range(h):
        for x in range(w):
            if rows[y][x] == "#":
                continue
            near = any(0 <= y + dy < h and 0 <= x + dx < w
                       and rows[y + dy][x + dx] == "#"
                       for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
            if near:
                p[x0 + x, y0 + y] = edge + (255,)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch == "#":
                d = rng.spread(amp)
                p[x0 + x, y0 + y] = (clamp(colour[0] + d),
                                     clamp(colour[1] + d),
                                     clamp(colour[2] + d), 255)


def widgets_png():
    """The hotbar strip, the selection box and the three button states.

    The strip is vanilla's construction rather than a guess at it: a black
    outline, a light bevel, then a dark interior at alpha 186, which is the
    alpha the real widgets.png uses. The old stub sat at 160 and let so much
    world through that the bar took the colour of whatever was behind it,
    which in a forest is green.
    """
    out = img(256, 256)
    p = px_of(out)
    for y in range(22):
        for x in range(182):
            if x + y < 1 or (181 - x) + y < 1 or \
                    x + (21 - y) < 1 or (181 - x) + (21 - y) < 1:
                continue
            if x == 0 or y == 0 or x == 181 or y == 21:
                p[x, y] = (0, 0, 0, 255)
            elif x == 1 or y == 1:
                p[x, y] = (198, 198, 198, 255)
            elif x == 180 or y == 20:
                p[x, y] = (86, 86, 86, 255)
            else:
                p[x, y] = (40, 40, 40, 186)
    for i in range(1, 9):                       # cell separators
        x0 = 1 + i * 20
        for y in range(2, 20):
            p[x0, y] = (92, 92, 92, 255)
            p[x0 + 1, y] = (58, 58, 58, 255)
    # selection box 24x24 at (0,22): a bright two pixel outline
    for i in range(24):
        for k in (0, 1, 22, 23):
            p[i, 22 + k] = (222, 222, 222, 255)
            p[k, 22 + i] = (222, 222, 222, 255)
    # three 200x20 button states at y 46 / 66 / 86
    for s, tone in enumerate(((90, 90, 90), (130, 130, 140), (150, 150, 180))):
        y0 = 46 + s * 20
        for y in range(20):
            for x in range(200):
                edge = x < 1 or y < 1 or x > 198 or y > 18
                p[x, y0 + y] = (shade(tone, -40) if edge else tone) + (255,)
    return out


def icons_png():
    """Hearts, haunches, armour, bubbles, the crosshair and the XP bar.

    The colours are vanilla's measured means: a full heart is (241,24,24),
    which is a bright red rather than the dull one the first stub used, and
    a full haunch is (175,97,70).
    """
    out = img(256, 256)
    p = px_of(out)
    rng = Rng(fnv("icons"))
    for i in range(15):                          # crosshair 15x15
        if abs(i - 7) > 1:
            p[i, 7] = (255, 255, 255, 200)
            p[7, i] = (255, 255, 255, 200)
    hearts = [(16, (25, 25, 25)), (25, (60, 30, 30)), (52, (241, 24, 24)),
              (61, (241, 24, 24)), (70, (255, 110, 110)),
              (79, (255, 110, 110)), (88, (140, 200, 60)),
              (97, (140, 200, 60)), (106, (170, 230, 90)),
              (115, (170, 230, 90)), (124, (60, 60, 60)), (133, (60, 60, 60)),
              (142, (100, 100, 100)), (151, (100, 100, 100)),
              (160, (240, 210, 60)), (169, (240, 210, 60))]
    for x0, col in hearts:
        stencil(p, x0, 0, HEART, col, rng)
    for x0, col in ((16, (52, 52, 52)), (25, (150, 150, 158)),
                    (34, (206, 206, 214))):
        stencil(p, x0, 9, ARMOUR, col, rng)
    for x0, col in ((16, (150, 210, 240)), (25, (100, 160, 210))):
        stencil(p, x0, 18, BUBBLE, col, rng)
    haunch = [(16, (30, 30, 30)), (52, (175, 97, 70)), (61, (175, 97, 70)),
              (88, (140, 170, 80)), (97, (140, 170, 80)), (133, (52, 52, 40))]
    for x0, col in haunch:
        stencil(p, x0, 27, HAUNCH, col, rng)
    for y in range(5):                            # xp bar, empty then full
        for x in range(182):
            p[x, 64 + y] = (40, 40, 40, 255)
            p[x, 69 + y] = ((126, 226, 46) if 0 < y < 4 else
                            (70, 150, 30)) + (255,)
    return out


def bars_png():
    out = img(256, 256)
    p = px_of(out)
    for y in range(5):
        for x in range(182):
            p[x, y] = (60, 20, 50, 255)
            p[x, 5 + y] = (236, 96, 190, 255)
    return out


# --------------------------------------------------------------------- fonts
# A 5x7 glyph per printable ASCII character, one hex digit per row giving the
# five columns. Hand written here rather than rendered from a system font,
# because a font available on the build machine is neither guaranteed nor
# deterministic, and the C renderer derives each character's advance from the
# rightmost opaque column of its cell.
GLYPHS = {
    " ": "...../...../...../...../...../...../.....",
    "!": "..#../..#../..#../..#../..#../...../..#..",
    "\"": ".#.#./.#.#./...../...../...../...../.....",
    "#": ".#.#./.#.#./#####/.#.#./#####/.#.#./.....",
    "$": "..#../.####/#.#../.###./..#.#/####./..#..",
    "%": "##..#/##..#/...#./..#../.#.../#..##/#..##",
    "&": ".##../#..#./.##../.##.#/#..##/#..#./.##.#",
    "'": "..#../..#../...../...../...../...../.....",
    "(": "...#./..#../.#.../.#.../.#.../..#../...#.",
    ")": ".#.../..#../...#./...#./...#./..#../.#...",
    "*": "...../#.#.#/.###./#####/.###./#.#.#/.....",
    "+": "...../..#../..#../#####/..#../..#../.....",
    ",": "...../...../...../...../..#../..#../.#...",
    "-": "...../...../...../#####/...../...../.....",
    ".": "...../...../...../...../...../..#../..#..",
    "/": "....#/....#/...#./..#../.#.../#..../#....",
    "0": ".###./#...#/#..##/#.#.#/##..#/#...#/.###.",
    "1": "..#../.##../..#../..#../..#../..#../.###.",
    "2": ".###./#...#/....#/...#./..#../.#.../#####",
    "3": "#####/...#./..#../...#./....#/#...#/.###.",
    "4": "...#./..##./.#.#./#..#./#####/...#./...#.",
    "5": "#####/#..../####./....#/....#/#...#/.###.",
    "6": "..##./.#.../#..../####./#...#/#...#/.###.",
    "7": "#####/....#/...#./..#../.#.../.#.../.#...",
    "8": ".###./#...#/#...#/.###./#...#/#...#/.###.",
    "9": ".###./#...#/#...#/.####/....#/...#./.##..",
    ":": "...../..#../..#../...../..#../..#../.....",
    ";": "...../..#../..#../...../..#../..#../.#...",
    "<": "...#./..#../.#.../#..../.#.../..#../...#.",
    "=": "...../...../#####/...../#####/...../.....",
    ">": ".#.../..#../...#./....#/...#./..#../.#...",
    "?": ".###./#...#/....#/...#./..#../...../..#..",
    "@": ".###./#...#/#.###/#.#.#/#.###/#..../.###.",
    "A": ".###./#...#/#...#/#####/#...#/#...#/#...#",
    "B": "####./#...#/#...#/####./#...#/#...#/####.",
    "C": ".###./#...#/#..../#..../#..../#...#/.###.",
    "D": "###../#..#./#...#/#...#/#...#/#..#./###..",
    "E": "#####/#..../#..../####./#..../#..../#####",
    "F": "#####/#..../#..../####./#..../#..../#....",
    "G": ".###./#...#/#..../#.###/#...#/#...#/.####",
    "H": "#...#/#...#/#...#/#####/#...#/#...#/#...#",
    "I": ".###./..#../..#../..#../..#../..#../.###.",
    "J": "....#/....#/....#/....#/#...#/#...#/.###.",
    "K": "#...#/#..#./#.#../##.../#.#../#..#./#...#",
    "L": "#..../#..../#..../#..../#..../#..../#####",
    "M": "#...#/##.##/#.#.#/#.#.#/#...#/#...#/#...#",
    "N": "#...#/##..#/#.#.#/#..##/#...#/#...#/#...#",
    "O": ".###./#...#/#...#/#...#/#...#/#...#/.###.",
    "P": "####./#...#/#...#/####./#..../#..../#....",
    "Q": ".###./#...#/#...#/#...#/#.#.#/#..#./.##.#",
    "R": "####./#...#/#...#/####./#.#../#..#./#...#",
    "S": ".####/#..../#..../.###./....#/....#/####.",
    "T": "#####/..#../..#../..#../..#../..#../..#..",
    "U": "#...#/#...#/#...#/#...#/#...#/#...#/.###.",
    "V": "#...#/#...#/#...#/#...#/#...#/.#.#./..#..",
    "W": "#...#/#...#/#...#/#.#.#/#.#.#/##.##/#...#",
    "X": "#...#/#...#/.#.#./..#../.#.#./#...#/#...#",
    "Y": "#...#/#...#/.#.#./..#../..#../..#../..#..",
    "Z": "#####/....#/...#./..#../.#.../#..../#####",
    "[": ".###./.#.../.#.../.#.../.#.../.#.../.###.",
    "\\": "#..../#..../.#.../..#../...#./....#/....#",
    "]": ".###./...#./...#./...#./...#./...#./.###.",
    "^": "..#../.#.#./#...#/...../...../...../.....",
    "_": "...../...../...../...../...../...../#####",
    "`": ".#.../..#../...../...../...../...../.....",
    "a": "...../...../.###./....#/.####/#...#/.####",
    "b": "#..../#..../####./#...#/#...#/#...#/####.",
    "c": "...../...../.###./#..../#..../#...#/.###.",
    "d": "....#/....#/.####/#...#/#...#/#...#/.####",
    "e": "...../...../.###./#...#/#####/#..../.###.",
    "f": "..##./.#..#/.#.../####./.#.../.#.../.#...",
    "g": "...../.####/#...#/#...#/.####/....#/.###.",
    "h": "#..../#..../####./#...#/#...#/#...#/#...#",
    "i": "..#../...../.##../..#../..#../..#../.###.",
    "j": "...#./...../..##./...#./...#./#..#./.##..",
    "k": "#..../#..../#..#./#.#../##.../#.#../#..#.",
    "l": ".##../..#../..#../..#../..#../..#../.###.",
    "m": "...../...../##.#./#.#.#/#.#.#/#...#/#...#",
    "n": "...../...../####./#...#/#...#/#...#/#...#",
    "o": "...../...../.###./#...#/#...#/#...#/.###.",
    "p": "...../...../####./#...#/####./#..../#....",
    "q": "...../...../.####/#...#/.####/....#/....#",
    "r": "...../...../#.##./##..#/#..../#..../#....",
    "s": "...../...../.####/#..../.###./....#/####.",
    "t": ".#.../.#.../####./.#.../.#.../.#..#/..##.",
    "u": "...../...../#...#/#...#/#...#/#..##/.##.#",
    "v": "...../...../#...#/#...#/#...#/.#.#./..#..",
    "w": "...../...../#...#/#...#/#.#.#/#.#.#/.#.#.",
    "x": "...../...../#...#/.#.#./..#../.#.#./#...#",
    "y": "...../...../#...#/#...#/.####/....#/.###.",
    "z": "...../...../#####/...#./..#../.#.../#####",
    "{": "...##/..#../..#../.#.../..#../..#../...##",
    "|": "..#../..#../..#../..#../..#../..#../..#..",
    "}": "##.../..#../..#../...#./..#../..#../##...",
    "~": "...../...../.#..#/#.#.#/#..#./...../.....",
}


def ascii_png():
    """The 128x128 sheet, sixteen 8x8 cells to a row, character c at cell
    (c%16, c//16). That is where vanilla's FontRenderer looks and where
    hud.c font_init looks, so the layout is not ours to choose. hud.c also
    derives each character's advance from the rightmost opaque column of its
    cell, which is why the glyphs are left aligned in a five wide box."""
    out = img(128, 128)
    p = px_of(out)
    for code in range(32, 127):
        g = GLYPHS.get(chr(code))
        if not g:
            continue
        cx, cy = (code % 16) * 8, (code // 16) * 8
        for row, bits in enumerate(g.split("/")):
            for col, ch in enumerate(bits):
                if ch == "#":
                    p[cx + col, cy + row] = (255, 255, 255, 255)
    return out


# ---------------------------------------------------------------- everything
def colormap_png(corners):
    """A biome colormap, bilinear across the four corners of the vanilla one.

    Vanilla indexes it by temperature across and humidity down, and the four
    corners it actually reaches are what these are: desert, plains, taiga and
    forest, read straight off the real map. Getting this right matters more
    than any single texture, because grass, leaves, tallgrass and vines are
    all near-grey textures that the colormap alone makes green. The earlier
    stub put the green in BOTH, which is what turned a canopy black.
    """
    hot_dry, hot_wet, cold_dry, cold_wet = corners
    im = img(256, 256)
    p = px_of(im)
    for j in range(256):
        wet = 1.0 - j / 255.0
        for i in range(256):
            hot = 1.0 - i / 255.0
            c = []
            for k in range(3):
                dry = hot_dry[k] * hot + cold_dry[k] * (1 - hot)
                wt = hot_wet[k] * hot + cold_wet[k] * (1 - hot)
                c.append(clamp(round(dry * (1 - wet) + wt * wet)))
            p[i, j] = tuple(c) + (255,)
    return im


# The colormaps are SOLVED, not copied. A tinted texture renders as
#
#   albedo * colormap / 255 * DAYLIGHT_FACE
#
# and the palette says what that has to come out as, so with the albedo
# pinned at TINTED_GREY the colormap is the only unknown. `solve` inverts
# it. The four corners keep vanilla's biome SHAPE, that a desert is
# yellower and a taiga greyer, by taking the vanilla corners' ratios about
# their own mean and re-centring them on the palette entry: grass block 2 at
# (95,159,53) and leaves 18 at (32,105,28).
_VANILLA_GRASS = ((191, 183, 85), (121, 192, 90), (150, 180, 120),
                  (134, 183, 131))
_VANILLA_FOLIAGE = ((174, 164, 42), (89, 174, 48), (120, 166, 80),
                    (104, 164, 100))


# What is left after solving. magma/core/shade.c composites a fragment as
# texel * tint * (lscalar * ao) * lightmap, with the tint AND the lightmap
# per channel, and then pulls every channel toward white by brightness_mix.
# So the residual is per channel by construction and no single constant
# lands. Solving against the mean of the four corners also aims at the
# average biome rather than the one the probe stands in. This is the gap
# that leaves, measured with the engine's own flat_shade instrument on a
# grass top face in open daylight, and applied to both maps because one
# biome column drives both.
COLORMAP_TRIM = (0.801, 1.0, 0.465)


def solve(corners, target):
    centre = [sum(c[k] for c in corners) / 4.0 for k in range(3)]
    want = [target[k] * COLORMAP_TRIM[k] * 255.0
            / (TINTED_GREY * DAYLIGHT_FACE) for k in range(3)]
    return tuple(tuple(clamp(round(c[k] * want[k] / centre[k]))
                       for k in range(3)) for c in corners)


GRASS_CORNERS = solve(_VANILLA_GRASS, NETHERITE_COLORS[2])
FOLIAGE_CORNERS = solve(_VANILLA_FOLIAGE, NETHERITE_COLORS[18])


# Default-skin rects in the 64x64 unwrap. game/hand.c textures the
# first-person arm from texU=40,texV=16 and the inventory preview walks the
# whole net, so painting the regions separately is what makes both read as a
# person instead of one coloured slab.
SKIN_HEAD = (0, 0, 32, 16)
SKIN_SHIRT = ((16, 16, 40, 32), (16, 32, 40, 48))
SKIN_LEGS = ((0, 16, 16, 32), (0, 32, 16, 48), (0, 48, 16, 64))
SKIN_ARMS = ((40, 16, 56, 32), (32, 48, 48, 64))
SKIN_TONE = (198, 152, 110)
SKIN_SLEEVE = (56, 132, 136)


def player_skin_png(name):
    rng = Rng(fnv(name))

    def paint(x0, y0, x1, y1, col, amp=7):
        for y in range(y0, y1):
            for x in range(x0, x1):
                d = rng.spread(amp)
                p[x, y] = (clamp(col[0] + d), clamp(col[1] + d),
                           clamp(col[2] + d), 255)

    im = img(64, 64)
    p = px_of(im)
    paint(0, 0, 64, 64, SKIN_TONE)
    for rect in SKIN_SHIRT:
        paint(rect[0], rect[1], rect[2], rect[3], SKIN_SLEEVE)
    for rect in SKIN_LEGS:
        paint(rect[0], rect[1], rect[2], rect[3], (62, 62, 132))
    # The arm net is four faces side by side. A sleeve across the top of it
    # and a shaded far side give the first-person hand something to be, since
    # a single flat fill there is the whole held arm in every frame.
    for x0, y0, x1, y1 in SKIN_ARMS:
        paint(x0, y0, x1, y1, SKIN_TONE, 5)
        paint(x0, y0, x1, y0 + 4, SKIN_SLEEVE, 5)
        for x in range(x0 + 8, x1):
            for y in range(y0, y1):
                p[x, y] = shade(p[x, y][:3], -22) + (255,)
        for y in range(y0 + 4, y1):
            p[x0, y] = shade(p[x0, y][:3], -16) + (255,)
    for y in range(4, 12):                       # hair on the head rect
        for x in range(8, 16):
            p[x, y] = (68, 44, 26, 255)
    for x in (10, 13):                           # eyes on the face front
        p[x, 12] = (32, 32, 40, 255)
        p[x, 13] = (240, 240, 240, 255)
    return im


def skin_png(name, w=64, h=64):
    """A player or mob skin. The renderers read sub-rects of these by
    hand written UVs, so what matters is that every texel is opaque and the
    body reads as one colour; a transparent one leaves holes in the model."""
    rng = Rng(fnv(name))
    base = hsv((fnv(name) % 997) / 997.0, 0.42, 0.62)
    im = img(w, h, base + (255,))
    p = px_of(im)
    for y in range(h):
        for x in range(w):
            d = rng.spread(7)
            p[x, y] = (clamp(base[0] + d), clamp(base[1] + d),
                       clamp(base[2] + d), 255)
    return im


def strip_png(name, index, total, frames, size):
    """An animated block strip: frames stacked vertically, each the same
    tile redrawn with the frame folded into its seed, so the animation
    actually moves."""
    im = img(size, size * frames)
    for f in range(frames):
        im.paste(block_tile(name, index, total, size, salt=f + 1), (0, f * size))
    return im


def sun_png():
    im = img(32, 32)
    p = px_of(im)
    for y in range(32):
        for x in range(32):
            d = abs(x - 15.5) + abs(y - 15.5)
            if d < 15:
                p[x, y] = (255, 244, 190, 255)
    return im


def moon_phases_png():
    im = img(128, 64)
    p = px_of(im)
    for cell in range(8):
        ox, oy = (cell % 4) * 32, (cell // 4) * 32
        for y in range(32):
            for x in range(32):
                if abs(x - 15.5) + abs(y - 15.5) < 15:
                    p[ox + x, oy + y] = (226, 226, 232, 255)
    return im


def clouds_png():
    im = img(256, 256)
    p = px_of(im)
    rng = Rng(fnv("clouds"))
    grid = [[0] * 32 for _ in range(32)]
    for gy in range(32):
        for gx in range(32):
            grid[gy][gx] = 1 if rng.below(5) < 2 else 0
    for y in range(256):
        for x in range(256):
            if grid[y // 8][x // 8]:
                p[x, y] = (255, 255, 255, 200)
    return im


def end_sky_png():
    im = img(128, 128)
    p = px_of(im)
    rng = Rng(fnv("end_sky"))
    for y in range(128):
        for x in range(128):
            v = 18 + rng.below(10)
            p[x, y] = (v, v // 2 + 6, v + 12, 255)
    return im


def underwater_png():
    im = img(16, 16)
    p = px_of(im)
    rng = Rng(fnv("underwater"))
    for y in range(16):
        for x in range(16):
            d = rng.spread(14)
            p[x, y] = (clamp(40 + d), clamp(96 + d), 235, 140)
    return im


def options_background_png():
    im = img(16, 16)
    p = px_of(im)
    rng = Rng(fnv("options_background"))
    for y in range(16):
        for x in range(16):
            d = rng.spread(10)
            p[x, y] = (clamp(56 + d), clamp(40 + d), clamp(28 + d), 255)
    return im


def particles_png(name, w, h):
    im = img(w, h)
    p = px_of(im)
    rng = Rng(fnv(name))
    for cy in range(0, h, 16):
        for cx in range(0, w, 16):
            col = hsv(rng.below(1000) / 1000.0, 0.5, 0.9)
            for y in range(2, 14):
                for x in range(2, 14):
                    p[cx + x, cy + y] = col + (200,)
    return im


# ----------------------------------------------------------------- packaging
def png_bytes(im):
    buf = io.BytesIO()
    im.save(buf, format="PNG")
    return buf.getvalue()


def build_pack(path):
    """Write the synthetic resource pack. Every member is drawn at its final
    size in RGBA, so nothing the engine's generators do to it resamples."""
    n_blocks = len(BLOCK_NAMES)
    n_items = len(ITEM_NAMES)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        def put(member, im):
            z.writestr(member, png_bytes(im))

        for i, name in enumerate(BLOCK_NAMES):
            if name in ANIMATED:
                frames, ft, size, seq_len = ANIMATED[name]
                put(TEX + "blocks/%s.png" % name,
                    strip_png(name, i, n_blocks, frames, size))
                seq = ([f for f in range(frames)] if seq_len == frames else
                       [f for f in range(frames)]
                       + [frames - 1 - f for f in range(seq_len - frames)])
                z.writestr(TEX + "blocks/%s.png.mcmeta" % name,
                           json.dumps({"animation": {"frametime": ft,
                                                     "frames": seq}}))
            elif name == "portal":
                put(TEX + "blocks/portal.png",
                    strip_png(name, i, n_blocks, PORTAL_FRAMES, 16))
            else:
                put(TEX + "blocks/%s.png" % name,
                    block_tile(name, i, n_blocks))
        for i, name in enumerate(ITEM_NAMES):
            put(TEX + "items/%s.png" % name, item_icon(name, i, n_items))
        put(TEX + "gui/container/inventory.png", inventory_png())
        put(TEX + "gui/container/crafting_table.png", crafting_table_png())
        put(TEX + "gui/container/furnace.png", furnace_png())
        put(TEX + "gui/container/generic_54.png", generic_54_png())
        put(TEX + "gui/widgets.png", widgets_png())
        put(TEX + "gui/icons.png", icons_png())
        put(TEX + "gui/bars.png", bars_png())
        put(TEX + "gui/options_background.png", options_background_png())
        put(TEX + "font/ascii.png", ascii_png())
        put(TEX + "misc/underwater.png", underwater_png())
        put(TEX + "colormap/grass.png", colormap_png(GRASS_CORNERS))
        put(TEX + "colormap/foliage.png", colormap_png(FOLIAGE_CORNERS))
        put(TEX + "environment/sun.png", sun_png())
        put(TEX + "environment/moon_phases.png", moon_phases_png())
        put(TEX + "environment/clouds.png", clouds_png())
        put(TEX + "environment/end_sky.png", end_sky_png())
        for member, w, h in MOBS:
            if member in ("steve.png", "alex.png"):
                put(TEX + "entity/" + member, player_skin_png(member))
            elif member in ("explosion.png",):
                put(TEX + "entity/" + member, particles_png(member, w, h))
            else:
                put(TEX + "entity/" + member, skin_png(member, w, h))
        put(TEX + "particle/particles.png",
            particles_png("particles.png", 128, 128))
        for layer in ARMOR_LAYERS:
            put(TEX + "models/armor/%s.png" % layer, skin_png(layer, 64, 32))
    return path


def digests(assets):
    out = {}
    for h in HEADERS:
        with open(os.path.join(assets, h), "rb") as f:
            out[h] = hashlib.sha256(f.read()).hexdigest()
    return out


def stamp(assets):
    """Prepend the provenance banner and record what was generated."""
    for h in HEADERS:
        p = os.path.join(assets, h)
        with open(p, "r") as f:
            body = f.read()
        if body.startswith("/* STUB TEXTURES"):
            continue
        with open(p, "w") as f:
            f.write(BANNER + body)
    d = digests(assets)
    with open(os.path.join(assets, "STUB_ATLASES"), "w") as f:
        f.write("stub_atlases.py v%d\n" % STUB_VERSION)
        for h in HEADERS:
            f.write("%s  %s\n" % (d[h], h))
    root = os.path.dirname(os.path.dirname(assets))
    digest = hashlib.sha256("".join(d[h] for h in HEADERS).encode()).hexdigest()
    with open(os.path.join(root, ".bedrock-rl-assets"), "w") as f:
        f.write("kind=procedural\n")
        f.write("source=bedrock-rl-stub-atlases-v%d\n" % STUB_VERSION)
        f.write("sha256=%s\n" % digest)
    return d


def generate(netherite_home, keep_pack=None):
    assets = os.path.join(netherite_home, "magma", "assets")
    if not os.path.isdir(assets):
        raise SystemExit("no magma/assets under " + netherite_home)
    tmp = tempfile.mkdtemp(prefix="stub_pack_")
    pack = build_pack(os.path.join(tmp, "stub_resources.jar"))
    env = dict(os.environ, MC_JAR=pack)
    subprocess.run(["bash", "scripts/bootstrap_assets.sh"],
                   cwd=netherite_home, env=env, check=True)
    d = stamp(assets)
    if keep_pack:
        os.replace(pack, keep_pack)
    else:
        os.remove(pack)
        os.rmdir(tmp)
    return d


def main():
    ap = argparse.ArgumentParser(
        description="generate netherite's texture headers without a jar")
    ap.add_argument("--netherite-home",
                    default=os.environ.get("NETHERITE_HOME",
                                           os.path.expanduser("~/netherite")))
    ap.add_argument("--keep-pack", metavar="PATH",
                    help="write the synthetic resource pack here for "
                         "inspection instead of deleting it")
    ap.add_argument("--print-digests", action="store_true",
                    help="print each header's sha256, which is how two "
                         "generations are compared")
    a = ap.parse_args()
    d = generate(os.path.expanduser(a.netherite_home), a.keep_pack)
    if a.print_digests:
        for h in HEADERS:
            print("%s  %s" % (d[h], h))
    print("stub atlases generated in %s/magma/assets (v%d)"
          % (a.netherite_home, STUB_VERSION))
    return 0


if __name__ == "__main__":
    sys.exit(main())
